### ISSUE TITLE
Hukamnama not up-to-date

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#324] opened 2018-03-06 06:00 UTC
Please select which platform you are using:-
Web Version

Feedback Type
HUKAMNAMA

What went wrong?
Excuse me, why this HUKAMNAMA is different?Having HUKAMNAMA up to date, every morning.
 
What should have happened instead?
Update the HUKAMNAMA every morning.
    
How can the issue be recreated by our team?
Having HUKAMNAMA up to date, every morning.May be it shows the yesterday's HUKAMNAMA. 

Which web browser are using?
Internet Explorer Samsung: 6.4.10.5

Operating System
Linux

Name
Harjot Singh

**Comment by bogas04** [comment] 2018-03-06 06:03
I love how it's slightly passive aggressive with the "Excuse me".

Maybe it's a timezone issue? I mean, do we update the Hukamnama as soon it comes on SGPC website?

**Comment by prebhdevsingh** [comment] 2018-03-06 13:00
No, our script is broken. It does not update automatically.

**Comment by bogas04** [comment] 2018-03-18 13:03
Duplicate of #161

**Closed by bogas04** 2018-03-18 13:03 UTC
Labels: banidb, user-reports
