### ISSUE TITLE
Type dropdown not retaining index after search

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/SikhiToTheMax-Web#159] opened 2017-04-18 01:55 UTC
Search for a shabad using romanized words (transliteration)
Search using transliteration again
Words will be converted to Gurmukhi text and type drop down will revert to first letter search.

**Comment by ManjotS** [comment] 2018-01-25 19:15
This was fixed with #157 - unable to reproduce now.

**Closed by ManjotS** 2018-01-25 19:15 UTC
