### ISSUE TITLE
toggles do not persist

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#166] opened 2017-09-12 16:19 UTC
its very annoying. 

Recreate:

search for something, change display options. 
Click a shabad, display options are reset.

**Comment by ManjotS** [comment] 2017-11-05 04:31
@navdeepsinghkhalsa @bogas04 I believe this was resolved and can be closed

**Comment by bogas04** [comment] 2017-11-06 07:42
Can't reproduce, I guess it was fixed. Closing now.

**Closed by bogas04** 2017-11-06 07:42 UTC
Labels: bug
