### ISSUE TITLE
copying and pasting multiple lines has too many line returns

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#274] opened 2018-01-29 18:42 UTC
## What went wrong ?
copying and pasting multiple lines has too many line returns
```
 ਕੋਈ ਪੜਤਾ ਸਹਸਾਕਿਰਤਾ ਕੋਈ ਪੜੈ ਪੁਰਾਨਾ ॥
 
 koiee paRataa sahasaakirataa koiee paRai puraanaa ||
 
     Some read the Sanskrit scriptures, and some read the Puraanas.
 
 ਕੋਈ ਨਾਮੁ ਜਪੈ ਜਪਮਾਲੀ ਲਾਗੈ ਤਿਸੈ ਧਿਆਨਾ ॥
 
 koiee naam japai japamaalee laagai tisai dhiaaanaa ||
 
     Some meditate on the Naam, the Name of the Lord, and chant it on their malas, focusing on it in meditation.
 
 ਅਬ ਹੀ ਕਬ ਹੀ ਕਿਛੂ ਨ ਜਾਨਾ ਤੇਰਾ ਏਕੋ ਨਾਮੁ ਪਛਾਨਾ ॥੧॥
 
 ab hee kab hee kichhoo n jaanaa tayraa eko naam pachhaanaa ||1||
 
     I know nothing, now or ever; I recognize only Your One Name, Lord. ||1||
```

## What should have happened instead ?
gurbani with metadata (trans, etc) should not have multiple line returns

```
 ਕੋਈ ਪੜਤਾ ਸਹਸਾਕਿਰਤਾ ਕੋਈ ਪੜੈ ਪੁਰਾਨਾ ॥
 koiee paRataa sahasaakirataa koiee paRai puraanaa ||
 Some read the Sanskrit scriptures, and some read the Puraanas.
 
 ਕੋਈ ਨਾਮੁ ਜਪੈ ਜਪਮਾਲੀ ਲਾਗੈ ਤਿਸੈ ਧਿਆਨਾ ॥
 koiee naam japai japamaalee laagai tisai dhiaaanaa ||
 Some meditate on the Naam, the Name of the Lord, and chant it on their malas, focusing on it in meditation.
 
 ਅਬ ਹੀ ਕਬ ਹੀ ਕਿਛੂ ਨ ਜਾਨਾ ਤੇਰਾ ਏਕੋ ਨਾਮੁ ਪਛਾਨਾ ॥੧॥
 ab hee kab hee kichhoo n jaanaa tayraa eko naam pachhaanaa ||1||
 I know nothing, now or ever; I recognize only Your One Name, Lord. ||1||
```

**Comment by bogas04** [comment] 2018-01-30 07:43
Low priority?

**Comment by prebhdevsingh** [comment] 2018-01-30 20:46
Copy paste looks fine to me.

**Comment by tarunsingh5** [comment] 2018-02-07 00:18
agreed, this looks ok to me too, closing this issue for now - @ManjotS reopen if you think its an issue still

**Comment by ManjotS** [comment] 2018-02-07 00:21
leave it open as low priority. I gave an example on what the issue is in my description.

**Comment by tarunsingh5** [comment] 2018-02-07 00:22
i followed your issue and found it to be working as intended

**Closed** 2018-03-26 18:14 UTC
Labels: 3️⃣, 🎢 enhancement, 🔜 fixed-in-dev
