### ISSUE TITLE
Web User Bug Reports

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#377] opened 2018-03-31 09:35 UTC
Please select which platform you are using:-
Desktop Version

Feedback Type
Bug Reports

What went wrong?
the shabad line does not change quickly after updating latest version 
 
What should have happened instead?

    
How can the issue be recreated by our team?
plz fix it

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
sukhman preet

**Comment by bogas04** [comment] 2018-03-31 10:29
Can't quite understand the issue. Is it about placeholder animation by any chance?

**Comment by bogas04** [comment] 2018-04-02 06:04
@ManjotS need to contact Sukhman Preet about this too.

**Comment by bogas04** [comment] 2018-04-03 08:51
@tarunsingh5 could you please contact Sukhman jee as well? Thank you so much!

**Comment by bogas04** [comment] 2018-04-09 02:58
@ManjotS @tarunsingh5

**Comment by tarunsingh5** [comment] 2018-04-09 06:13
this is a duplicate of a bug filed in desktop - im going to close this as it is referring to the desktop app i believe

**Closed by tarunsingh5** 2018-04-09 06:13 UTC
Labels: user-reports
